//
//  JPDealBusinessNameModel.h
//  JiePos
//
//  Created by Jason_LJ on 2017/4/19.
//  Copyright © 2017年 Jason. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface JPDealBusinessNameModel : NSObject

/**
 "businessLicense": null,
 "landlinePhone": null,
 "taxRegistrationUrlId": null,
 "rate": null,
 "legal_person_certificate_url": null,
 "accountType": null,
 "singleMinimum": null,
 "businessLicenseStarttimeSt": null,
 "registerAddress": null,
 "accountBankNameId": null,
 "contactPhone": null,
 "merchantShortName": null,
 "feeType": null,
 "monthMaxnum": null,
 "alliedBankCode": null,
 "legalPersonCertificateUrlId": null,
 "applyPosTypeId": null,
 "accountName": null,
 "industryNo": null,
 "merchantStatusList": null,
 "instName2": null,
 "contractEndtimeSt": null,
 "legalPersonCertificateTypeId": null,
 "applyTimeSt": null,
 "businessDistrictCode": null,
 "businessLicenseStarttime": null,
 "openPermitsUrlId": null,
 "other_pic_url": null,
 "settlementPeriod": null,
 "organizationCodeUrlId": null,
 "fax": null,
 "registerCityCode": null,
 "mcc": null,
 "managementContent": null,
 "applyType": 2,
 "legalPersonName": null,
 "businessProvinceCode": null,
 "applyUserId": null,
 "cardAndBankUrlId": null,
 "businessCityCode": null,
 "taxRegistration": null,
 "contact": null,
 "singleMaxnum": null,
 "userBelongIdList": null,
 "businessLicenseEndtime": null,
 "agreementUrlId": null,
 "accountCityCode": null,
 "otherPicUrlId": null,
 "chnlCode": null,
 "idCardFrontUrlId": null,
 "accountBankBranchName": null,
 "businessZipCode": null,
 "dayMaxnum": null,
 "level1": null,
 "instName1": null,
 "functionList": null,
 "contractStarttime": null,
 "merchantName": "曹雪芹",
 "agreement_url": null,
 "applyTime": null,
 "applyPosType": null,
 "contractEndtime": null,
 "organization_code_url": null,
 "merchantCategory": null,
 "store_pic_url": null,
 "rates": null,
 "registerDistrictCode": null,
 "singleMaxMoney": null,
 "merchantType": 1,
 "open_permits_url": null,
 "username": null,
 "registeredCapital": null,
 "contractNumber": null,
 "idCardBackUrlId": null,
 "businessAddress": null,
 "industryType": null,
 "accountIdcard": null,
 "merchantNo": "998320582110001",
 "instId": null,
 "registerProvinceCode": null,
 "legalPersonCertificate": null,
 "bankCardFrontUrlId": null,
 "merchantId": 484,
 "bankCardBackUrlId": null,
 "tax_registration_url": null,
 "accountProvinceCode": null,
 "payChannels": null,
 "level2": null,
 "parentMerchantId": null,
 "storePicUrlId": null,
 "qrcodeId": null,
 "merchantStatus": null,
 "businessLicenseUrlId": null,
 "organizationCode": null,
 "functions": null,
 "business_license_url": null,
 "account": null,
 "contactMobilePhone": null,
 "businessLicenseEndtimeSt": null,
 "registerZipCode": null,
 "businessPersonId": null,
 "contractStarttimeSt": null
 */
@property (nonatomic, assign) NSInteger applyType;
@property (nonatomic, copy) NSString *merchantName;
@property (nonatomic, assign) NSInteger merchantType;
@property (nonatomic, copy) NSString *merchantNo;
@property (nonatomic, copy) NSString *merchantId;
@end
